### ISSUE TITLE
`make test` fails on a fresh install

### ISSUE THREAD

**Issue by karlht** [mozilla-services/ailoads-loop#5]
This is probably more of a documentation bug than anything else:  Is there a testing account that needs to be filled in to `FXA_EXISTING_EMAIL` before `make test` will function? 

```
[2] 14:40 (ttys001) kthiessen@kthiessen-16107:~/Library/github/mozilla-services/ailoads-loop 593$ make test
bash -c "source loadtest.env && LOOP_SERVER_URL=https://loop.stage.mozaws.net:443 /Users/kthiessen/Library/github/mozilla-services/ailoads-loop/venv/bin/ailoads -v -d 30"
Traceback (most recent call last):
  File "/Users/kthiessen/Library/github/mozilla-services/ailoads-loop/venv/bin/ailoads", line 9, in <module>
    load_entry_point('ailoads==0.1', 'console_scripts', 'ailoads')()
  File "/Users/kthiessen/Library/github/mozilla-services/ailoads-loop/venv/lib/python3.4/site-packages/ailoads/run.py", line 73, in main
    resolve_name(args.scenarii)
 File "/Users/kthiessen/Library/github/mozilla-services/ailoads-loop/venv/lib/python3.4/site-packages/ailoads/run.py", line 15, in resolve_name
    __import__(name)
  File "/Users/kthiessen/Library/github/mozilla-services/ailoads-loop/loadtest.py", line 38, in <module>
    FXA_EMAIL = extract_email_from_assertion(FXA_BROWSERID_ASSERTION)
  File "/Users/kthiessen/Library/github/mozilla-services/ailoads-loop/loadtest.py", line 33, in extract_email_from_assertion
    decoded_fragment = urlsafe_b64decode(fragment).decode('utf-8')
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/base64.py", line 135, in urlsafe_b64decode
    return b64decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/base64.py", line 90, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
make: *** [test] Error 1
```

**Comment by karlht** [comment]
Ah, this just needs a `make setup_random` first.  Perhaps we could copy over the `README.md` from https://github.com/mozilla-services/ailoads-syncto ?
